import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { RiWhatsappFill } from "react-icons/ri";
import { MdAlarm } from "react-icons/md";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Top Bar */}
        <div className="w-full bg-primary-green text-white text-base py-2 flex flex-wrap justify-center gap-8">
          <span><MdAlarm className="inline mr-1" size={18} />Working Hours 24*7</span>
          <span>AHM +91-7043008890</span>
          <span>BLR +91-6366209990</span>
        </div>
        {/* Header */}
        <header className="w-full flex flex-col sm:flex-row items-center justify-between px-8 py-4 bg-card-bg shadow-sm sticky top-0 z-10">
          <div className="flex items-center gap-2">
            <Image src="/logo.png" alt="GIOSTAR Logo" width={96} height={96} />
            <span className="text-2xl font-bold text-primary-green">GIOSTAR INDIA</span>
          </div>
          <nav className="flex gap-6 mt-2 sm:mt-0 text-[var(--foreground)] font-medium">
            <Link href="/" className="hover:text-primary-teal smooth-transition">Home</Link>
            <Link href="/about" className="hover:text-primary-teal smooth-transition">About Us</Link>
            <a href="#therapy" className="hover:text-primary-teal smooth-transition">Therapy</a>
            <Link href="/ahmedabad-centre" className="hover:text-primary-teal smooth-transition">Ahmedabad Centre</Link>
            <Link href="/bangalore-centre" className="hover:text-primary-teal smooth-transition">Bangalore Centre</Link>
            <Link href="/contact" className="hover:text-primary-teal smooth-transition">Contact Us</Link>
          </nav>
        </header>
        {/* Main Content */}
        {children}
        {/* Footer */}
        <footer className="bg-primary-green text-white py-10 px-4 mt-8 relative rounded-b-xl">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-start gap-12 md:gap-0">
            {/* Left: Logo, Brand, Description */}
            <div className="flex flex-col items-center md:items-start w-full md:w-1/3 mb-8 md:mb-0">
              <div className="flex flex-col items-center md:items-start">
                <Image src="/logo.png" alt="GIOSTAR Logo" width={180} height={180} />
              </div>
              <p className="mt-6 text-center md:text-left text-white/90 max-w-xs text-base font-medium">
                <span className="font-bold">GIOSTAR India</span> is a leading network of hospitals and stem cell research centers, offering advanced regenerative treatments for various diseases and chronic conditions.
              </p>
            </div>
            {/* Right: Columns */}
            <div className="flex flex-1 flex-col md:flex-row justify-between w-full gap-12">
              {/* Quick Links */}
              <div>
                <div className="font-bold mb-2 text-lg">Quick Links</div>
                <ul className="space-y-1">
                  <li><a href="#therapy" className="hover:underline">Therapy</a></li>
                  <li><a href="#" className="hover:underline">Blogs & News</a></li>
                  <li><a href="#" className="hover:underline">Publications</a></li>
                  <li><a href="#" className="hover:underline">Executive Management</a></li>
                  <li><a href="#" className="hover:underline">Disclaimer</a></li>
                </ul>
              </div>
              {/* Hospitals */}
              <div>
                <div className="font-bold mb-2 text-lg">Hospitals</div>
                <ul className="space-y-1">
                  <li><Link href="/ahmedabad-centre" className="hover:underline">Ahmedabad</Link></li>
                  <li><Link href="/bangalore-centre" className="hover:underline">Bangalore</Link></li>
                  <li>Chandigarh</li>
                  <li>San Diego (USA)</li>
                </ul>
              </div>
              {/* Contact & Social */}
              <div>
                <div className="font-bold mb-2 text-lg">Contact</div>
                <ul className="space-y-2">
                  <li className="flex items-center gap-2"><span className="text-2xl"><i className="ri-youtube-fill"></i></span> YouTube</li>
                  <li className="flex items-center gap-2"><span className="text-2xl"><i className="ri-facebook-circle-fill"></i></span> Facebook</li>
                  <li className="flex items-center gap-2"><span className="text-2xl"><i className="ri-instagram-fill"></i></span> Instagram</li>
                  <li className="flex items-center gap-2"><span className="text-2xl"><i className="ri-linkedin-box-fill"></i></span> LinkedIn</li>
                  <li className="flex items-center gap-2"><span className="text-2xl"><i className="ri-mail-fill"></i></span> contact@giostar.com</li>
                </ul>
              </div>
            </div>
          </div>
          {/* Copyright */}
          <div className="text-center text-xs mt-10 text-white/80">Copyright © 2025 GIOSTAR | Managed by digvisolutions</div>
          {/* WhatsApp Floating Button */}
          <a href="https://wa.me/917043008890" target="_blank" rel="noopener noreferrer" className="fixed bottom-6 right-6 z-50 bg-primary-green rounded-full shadow-lg p-3 hover:bg-green-600 transition-colors">
            <RiWhatsappFill size={56} color="#fff" />
          </a>
        </footer>
      </body>
    </html>
  );
}
